[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "PythonAutomataLibrary"
version = "0.1.0"
dependencies = [
    "numpy",
    "numba",
]

[tool.setuptools]
packages = ["PythonAutomataLibrary"]

[tool.setuptools.package-dir]
PythonAutomataLibrary = "."